
adm0_CHOICES         = [("GUATEMALA", "GUATEMALA"), ("OTROS", "OTROS")]



DEPARTAMENTO_CHOICES = [('Alta Verapaz', 'Alta Verapaz'),
                        ('Baja Verapaz', 'Baja Verapaz'),
                        ('Chimaltenango', 'Chimaltenango'),
                        ('Chiquimula', 'Chiquimula'),
                        ('El Progreso', 'El Progreso'),
                        ('Escuintla', 'Escuintla'),
                        ('Guatemala', 'Guatemala'),
                        ('Huehuetenango', 'Huehuetenango'),
                        ('Izabal', 'Izabal'),
                        ('Jalapa', 'Jalapa'),
                        ('Jutiapa', 'Jutiapa'),
                        ('Petén', 'Petén'),
                        ('Quetzaltenango', 'Quetzaltenango'),
                        ('Quiché', 'Quiché'),
                        ('Retalhuleu', 'Retalhuleu'),
                        ('Sacatepéquez', 'Sacatepéquez'),
                        ('San Marcos', 'San Marcos'),
                        ('Santa Rosa', 'Santa Rosa'),
                        ('Sololá', 'Sololá'),
                        ('Suchitepéquez', 'Suchitepéquez'),
                        ('Totonicapán', 'Totonicapán'),
                        ('Zacapa', 'Zacapa')]







MUNICIPIO_CHOICES    = [('Acatenango', 'Acatenango'),
                        ('Aguacatán', 'Aguacatán'),
                        ('Almolonga', 'Almolonga'),
                        ('Agua Blanca', 'Agua Blanca'),
                        ('Alotenango', 'Alotenango'),
                        ('Amatitlán', 'Amatitlán'),
                        ('Antigua Guatemala', 'Antigua Guatemala'),
                        ('Asunción Mita', 'Asunción Mita'),
                        ('Atescatempa', 'Atescatempa'),
                        ('Barberena', 'Barberena'),
                        ('Ayutla', 'Ayutla'),
                        ('Chinique', 'Chinique'),
                        ('Barillas', 'Barillas'),
                        ('Cabañas', 'Cabañas'),
                        ('Cabricán', 'Cabricán'),
                        ('Camotán', 'Camotán'),
                        ('Canillá', 'Canillá'),
                        ('Cantel', 'Cantel'),
                        ('Cahabón', 'Cahabón'),
                        ('Cajolá', 'Cajolá'),
                        ('Casillas', 'Casillas'),
                        ('Catarina', 'Catarina'),
                        ('Chahal', 'Chahal'),
                        ('El Adelanto', 'El Adelanto'),
                        ('Chajul', 'Chajul'),
                        ('Champerico', 'Champerico'),
                        ('Chichicastenango', 'Chichicastenango'),
                        ('Chiantla', 'Chiantla'),
                        ('Chicacao', 'Chicacao'),
                        ('Chicamán', 'Chicamán'),
                        ('Chiché', 'Chiché'),
                        ('Chimaltenango', 'Chimaltenango'),
                        ('Chinautla', 'Chinautla'),
                        ('Chiquimula', 'Chiquimula'),
                        ('Chiquimulilla', 'Chiquimulilla'),
                        ('Chisec', 'Chisec'),
                        ('Chuarrancho', 'Chuarrancho'),
                        ('Ciudad Vieja', 'Ciudad Vieja'),
                        ('Coatepeque', 'Coatepeque'),
                        ('Cobán', 'Cobán'),
                        ('Colomba', 'Colomba'),
                        ('Colotenango', 'Colotenango'),
                        ('Comalapa', 'Comalapa'),
                        ('Comapa', 'Comapa'),
                        ('Iztapa', 'Iztapa'),
                        ('Comitancillo', 'Comitancillo'),
                        ('Concepción', 'Concepción'),
                        ('Concepción Chiquirichapa', 'Concepción Chiquirichapa'),
                        ('Concepción Huista', 'Concepción Huista'),
                        ('Concepción Las Minas', 'Concepción Las Minas'),
                        ('Concepción Tutuapa', 'Concepción Tutuapa'),
                        ('Conguaco', 'Conguaco'),
                        ('San Gaspar Ixchil', 'San Gaspar Ixchil'),
                        ('Cubulco', 'Cubulco'),
                        ('Cunén', 'Cunén'),
                        ('Cuyotenango', 'Cuyotenango'),
                        ('Dolores', 'Dolores'),
                        ('Cuilapa', 'Cuilapa'),
                        ('Cuilco', 'Cuilco'),
                        ('El Asintal', 'El Asintal'),
                        ('El Chal', 'El Chal'),
                        ('Santa María Visitación', 'Santa María Visitación'),
                        ('El Chol', 'El Chol'),
                        ('El Estor', 'El Estor'),
                        ('El Jícaro', 'El Jícaro'),
                        ('El Palmar', 'El Palmar'),
                        ('El Progreso', 'El Progreso'),
                        ('Santo Domingo Suchitepéquez', 'Santo Domingo Suchitepéquez'),
                        ('El Quetzal', 'El Quetzal'),
                        ('El Rodeo', 'El Rodeo'),
                        ('El Tejar', 'El Tejar'),
                        ('El Tumbador', 'El Tumbador'),
                        ('Escuintla', 'Escuintla'),
                        ('Esquipulas', 'Esquipulas'),
                        ('Esquipulas Palo Gordo', 'Esquipulas Palo Gordo'),
                        ('Flores', 'Flores'),
                        ('Palestina de Los Altos', 'Palestina de Los Altos'),
                        ('Estanzuela', 'Estanzuela'),
                        ('Flores Costa Cuca', 'Flores Costa Cuca'),
                        ('Fraijanes', 'Fraijanes'),
                        ('Fray Bartolomé de Las Casas', 'Fray Bartolomé de Las Casas'),
                        ('Génova', 'Génova'),
                        ('Granados', 'Granados'),
                        ('Gualán', 'Gualán'),
                        ('Guanagazapa', 'Guanagazapa'),
                        ('Guastatoya', 'Guastatoya'),
                        ('Ixtahuacán', 'Ixtahuacán'),
                        ('Guatemala', 'Guatemala'),
                        ('Guazacapán', 'Guazacapán'),
                        ('Huehuetenango', 'Huehuetenango'),
                        ('Huitán', 'Huitán'),
                        ('Huité', 'Huité'),
                        ('Ipala', 'Ipala'),
                        ('Ixcán', 'Ixcán'),
                        ('Ixchiguán', 'Ixchiguán'),
                        ('Jacaltenango', 'Jacaltenango'),
                        ('Jalapa', 'Jalapa'),
                        ('Jalpatagua', 'Jalpatagua'),
                        ('La Libertad', 'La Libertad'),
                        ('Jerez', 'Jerez'),
                        ('La Democracia', 'La Democracia'),
                        ('La Esperanza', 'La Esperanza'),
                        ('La Libertad', 'La Libertad'),
                        ('Jocotán', 'Jocotán'),
                        ('Jocotenango', 'Jocotenango'),
                        ('Joyabaj', 'Joyabaj'),
                        ('San Antonio Sacatepéquez', 'San Antonio Sacatepéquez'),
                        ('Jutiapa', 'Jutiapa'),
                        ('La Blanca', 'La Blanca'),
                        ('San Bartolomé Milpas Altas', 'San Bartolomé Milpas Altas'),
                        ('La Democracia', 'La Democracia'),
                        ('La Gomera', 'La Gomera'),
                        ('La Reforma', 'La Reforma'),
                        ('La Unión', 'La Unión'),
                        ('Melchor de Mencos', 'Melchor de Mencos'),
                        ('Lago De Amatitlan', 'Lago De Amatitlan'),
                        ('Lago De Atitlan', 'Lago De Atitlan'),
                        ('San Jacinto', 'San Jacinto'),
                        ('Lanquín', 'Lanquín'),
                        ('Las Cruces', 'Las Cruces'),
                        ('Lívingston', 'Lívingston'),
                        ('Los Amates', 'Los Amates'),
                        ('Magdalena Milpas Altas', 'Magdalena Milpas Altas'),
                        ('Malacatán', 'Malacatán'),
                        ('Malacatancito', 'Malacatancito'),
                        ('San Lucas Sacatepéquez', 'San Lucas Sacatepéquez'),
                        ('Masagua', 'Masagua'),
                        ('Mataquescuintla', 'Mataquescuintla'),
                        ('Mixco', 'Mixco'),
                        ('Monjas', 'Monjas'),
                        ('Mazatenango', 'Mazatenango'),
                        ('Momostenango', 'Momostenango'),
                        ('San Sebastián Huehuetenango', 'San Sebastián Huehuetenango'),
                        ('Morales', 'Morales'),
                        ('Morazán', 'Morazán'),
                        ('Moyuta', 'Moyuta'),
                        ('Santa Apolonia', 'Santa Apolonia'),
                        ('Nahualá', 'Nahualá'),
                        ('Nebaj', 'Nebaj'),
                        ('Nentón', 'Nentón'),
                        ('Nueva Concepción', 'Nueva Concepción'),
                        ('San José Acatempa', 'San José Acatempa'),
                        ('Nueva Santa Rosa', 'Nueva Santa Rosa'),
                        ('Nuevo Progreso', 'Nuevo Progreso'),
                        ('Nuevo San Carlos', 'Nuevo San Carlos'),
                        ('Olopa', 'Olopa'),
                        ('Ocós', 'Ocós'),
                        ('Olintepeque', 'Olintepeque'),
                        ('San Benito', 'San Benito'),
                        ('Oratorio', 'Oratorio'),
                        ('Palín', 'Palín'),
                        ('San José Chacayá', 'San José Chacayá'),
                        ('Ostuncalco', 'Ostuncalco'),
                        ('Panajachel', 'Panajachel'),
                        ('San Bernardino', 'San Bernardino'),
                        ('Pachalum', 'Pachalum'),
                        ('Palencia', 'Palencia'),
                        ('Pajapita', 'Pajapita'),
                        ('Patzité', 'Patzité'),
                        ('Panzós', 'Panzós'),
                        ('Parramos', 'Parramos'),
                        ('San Carlos Alzatate', 'San Carlos Alzatate'),
                        ('Pasaco', 'Pasaco'),
                        ('Pastores', 'Pastores'),
                        ('Patulul', 'Patulul'),
                        ('Patzicía', 'Patzicía'),
                        ('Patzún', 'Patzún'),
                        ('Petapa', 'Petapa'),
                        ('Quesada', 'Quesada'),
                        ('San José Ojetenam', 'San José Ojetenam'),
                        ('Petatán', 'Petatán'),
                        ('Samayac', 'Samayac'),
                        ('Pochuta', 'Pochuta'),
                        ('Poptún', 'Poptún'),
                        ('Pueblo Nuevo', 'Pueblo Nuevo'),
                        ('Pueblo Nuevo Viñas', 'Pueblo Nuevo Viñas'),
                        ('Puerto Barrios', 'Puerto Barrios'),
                        ('Purulhá', 'Purulhá'),
                        ('Quetzaltenango', 'Quetzaltenango'),
                        ('Quezaltepeque', 'Quezaltepeque'),
                        ('San Cristóbal Cucho', 'San Cristóbal Cucho'),
                        ('Rabinal', 'Rabinal'),
                        ('Raxruhá', 'Raxruhá'),
                        ('Retalhuleu', 'Retalhuleu'),
                        ('Río Blanco', 'Río Blanco'),
                        ('Río Bravo', 'Río Bravo'),
                        ('Río Hondo', 'Río Hondo'),
                        ('Sacapulas', 'Sacapulas'),
                        ('Salamá', 'Salamá'),
                        ('Salcajá', 'Salcajá'),
                        ('San Agustín Acasaguastlán', 'San Agustín Acasaguastlán'),
                        ('San Andrés', 'San Andrés'),
                        ('San Andrés Itzapa', 'San Andrés Itzapa'),
                        ('San Andrés Sajcabajá', 'San Andrés Sajcabajá'),
                        ('San Andrés Semetabaj', 'San Andrés Semetabaj'),
                        ('San Andrés Villa Seca', 'San Andrés Villa Seca'),
                        ('San Andrés Xecul', 'San Andrés Xecul'),
                        ('San Antonio Aguas Calientes', 'San Antonio Aguas Calientes'),
                        ('San Cristóbal Totonicapán', 'San Cristóbal Totonicapán'),
                        ('San Cristóbal Verapaz', 'San Cristóbal Verapaz'),
                        ('San Antonio Huista', 'San Antonio Huista'),
                        ('San Antonio Ilotenango', 'San Antonio Ilotenango'),
                        ('San Antonio Palopó', 'San Antonio Palopó'),
                        ('San Antonio La Paz', 'San Antonio La Paz'),
                        ('San Antonio Suchitepéquez', 'San Antonio Suchitepéquez'),
                        ('San Bartolo', 'San Bartolo'),
                        ('San Bartolomé Jocotenango', 'San Bartolomé Jocotenango'),
                        ('San Carlos Sija', 'San Carlos Sija'),
                        ('San Cristóbal Acasaguastlán', 'San Cristóbal Acasaguastlán'),
                        ('San Diego', 'San Diego'),
                        ('San Felipe', 'San Felipe'),
                        ('San Francisco', 'San Francisco'),
                        ('San Gabriel', 'San Gabriel'),
                        ('San Francisco El Alto', 'San Francisco El Alto'),
                        ('San Francisco La Unión', 'San Francisco La Unión'),
                        ('San Francisco Zapotitlán', 'San Francisco Zapotitlán'),
                        ('San Jerónimo', 'San Jerónimo'),
                        ('San José', 'San José'),
                        ('San José', 'San José'),
                        ('San Jorge', 'San Jorge'),
                        ('San José del Golfo', 'San José del Golfo'),
                        ('San José El Ídolo', 'San José El Ídolo'),
                        ('San José La Arada', 'San José La Arada'),
                        ('San José La Máquina', 'San José La Máquina'),
                        ('San José Pinula', 'San José Pinula'),
                        ('San Juan Bautista', 'San Juan Bautista'),
                        ('San Juan Chamelco', 'San Juan Chamelco'),
                        ('San José Poaquil', 'San José Poaquil'),
                        ('San Juan Atitán', 'San Juan Atitán'),
                        ('San Juan Cotzal', 'San Juan Cotzal'),
                        ('San Juan Ermita', 'San Juan Ermita'),
                        ('San Lorenzo', 'San Lorenzo'),
                        ('San Juan Ixcoy', 'San Juan Ixcoy'),
                        ('San Juan La Laguna', 'San Juan La Laguna'),
                        ('San Juan Sacatepéquez', 'San Juan Sacatepéquez'),
                        ('San Juan Tecuaco', 'San Juan Tecuaco'),
                        ('San Lorenzo', 'San Lorenzo'),
                        ('San Lucas Tolimán', 'San Lucas Tolimán'),
                        ('San Luis', 'San Luis'),
                        ('San Luis Jilotepeque', 'San Luis Jilotepeque'),
                        ('San Miguel Sigüila', 'San Miguel Sigüila'),
                        ('San Manuel Chaparrón', 'San Manuel Chaparrón'),
                        ('San Martín Sacatepéquez', 'San Martín Sacatepéquez'),
                        ('San Marcos', 'San Marcos'),
                        ('San Marcos La Laguna', 'San Marcos La Laguna'),
                        ('San Martín Jilotepeque', 'San Martín Jilotepeque'),
                        ('San Martín Zapotitlán', 'San Martín Zapotitlán'),
                        ('San Mateo', 'San Mateo'),
                        ('San Mateo Ixtatán', 'San Mateo Ixtatán'),
                        ('San Miguel Acatán', 'San Miguel Acatán'),
                        ('San Miguel Ixtahuacán', 'San Miguel Ixtahuacán'),
                        ('San Miguel Chicaj', 'San Miguel Chicaj'),
                        ('San Miguel Dueñas', 'San Miguel Dueñas'),
                        ('San Miguel Panán', 'San Miguel Panán'),
                        ('San Pablo', 'San Pablo'),
                        ('San Pablo Jocopilas', 'San Pablo Jocopilas'),
                        ('San Pablo La Laguna', 'San Pablo La Laguna'),
                        ('San Rafael Pie de la Cuesta', 'San Rafael Pie de la Cuesta'),
                        ('San Pedro Ayampuc', 'San Pedro Ayampuc'),
                        ('San Pedro Carchá', 'San Pedro Carchá'),
                        ('San Pedro La Laguna', 'San Pedro La Laguna'),
                        ('San Pedro Jocopilas', 'San Pedro Jocopilas'),
                        ('San Pedro Sacatepéquez', 'San Pedro Sacatepéquez'),
                        ('San Pedro Necta', 'San Pedro Necta'),
                        ('San Pedro Pinula', 'San Pedro Pinula'),
                        ('San Pedro Sacatepéquez', 'San Pedro Sacatepéquez'),
                        ('San Rafael La Independencia', 'San Rafael La Independencia'),
                        ('San Rafael Las Flores', 'San Rafael Las Flores'),
                        ('San Rafael Petzal', 'San Rafael Petzal'),
                        ('San Raimundo', 'San Raimundo'),
                        ('San Sebastián', 'San Sebastián'),
                        ('San Sebastián Coatán', 'San Sebastián Coatán'),
                        ('San Vicente Pacaya', 'San Vicente Pacaya'),
                        ('Sanarate', 'Sanarate'),
                        ('Sansare', 'Sansare'),
                        ('Santa Ana', 'Santa Ana'),
                        ('Santa Ana Huista', 'Santa Ana Huista'),
                        ('Santa Bárbara', 'Santa Bárbara'),
                        ('Santa Bárbara', 'Santa Bárbara'),
                        ('Santa Catarina Pinula', 'Santa Catarina Pinula'),
                        ('Santa Catalina La Tinta', 'Santa Catalina La Tinta'),
                        ('Santa Catarina Barahona', 'Santa Catarina Barahona'),
                        ('Santa Clara La Laguna', 'Santa Clara La Laguna'),
                        ('Santa Catarina Ixtahuacán', 'Santa Catarina Ixtahuacán'),
                        ('Santa Cruz Balanyá', 'Santa Cruz Balanyá'),
                        ('Santa Cruz del Quiché', 'Santa Cruz del Quiché'),
                        ('Santa Cruz La Laguna', 'Santa Cruz La Laguna'),
                        ('Santa Cruz Muluá', 'Santa Cruz Muluá'),
                        ('Santa Catarina Mita', 'Santa Catarina Mita'),
                        ('Santa Catarina Palopó', 'Santa Catarina Palopó'),
                        ('Santa Cruz Naranjo', 'Santa Cruz Naranjo'),
                        ('Santa Cruz Verapaz', 'Santa Cruz Verapaz'),
                        ('Santa Lucía La Reforma', 'Santa Lucía La Reforma'),
                        ('Santa Lucía Milpas Altas', 'Santa Lucía Milpas Altas'),
                        ('Santa Eulalia', 'Santa Eulalia'),
                        ('Santa Lucía Cotzumalguapa', 'Santa Lucía Cotzumalguapa'),
                        ('Santa Lucía Utatlán', 'Santa Lucía Utatlán'),
                        ('Santo Domingo Xenacoj', 'Santo Domingo Xenacoj'),
                        ('Santa María Chiquimula', 'Santa María Chiquimula'),
                        ('Santa María de Jesús', 'Santa María de Jesús'),
                        ('Santa María Ixhuatán', 'Santa María Ixhuatán'),
                        ('Santa Rosa de Lima', 'Santa Rosa de Lima'),
                        ('Santo Tomás La Unión', 'Santo Tomás La Unión'),
                        ('Sayaxché', 'Sayaxché'),
                        ('Senahú', 'Senahú'),
                        ('Santiago Atitlán', 'Santiago Atitlán'),
                        ('Santiago Chimaltenango', 'Santiago Chimaltenango'),
                        ('Santiago Sacatepéquez', 'Santiago Sacatepéquez'),
                        ('Sibilia', 'Sibilia'),
                        ('Sibinal', 'Sibinal'),
                        ('Sipacapa', 'Sipacapa'),
                        ('Sipacate', 'Sipacate'),
                        ('Siquinalá', 'Siquinalá'),
                        ('Sololá', 'Sololá'),
                        ('Soloma', 'Soloma'),
                        ('Sumpango', 'Sumpango'),
                        ('Tacaná', 'Tacaná'),
                        ('Tactic', 'Tactic'),
                        ('Teculután', 'Teculután'),
                        ('Tajumulco', 'Tajumulco'),
                        ('Tamahú', 'Tamahú'),
                        ('Taxisco', 'Taxisco'),
                        ('Tecpán Guatemala', 'Tecpán Guatemala'),
                        ('Tectitán', 'Tectitán'),
                        ('Yupiltepeque', 'Yupiltepeque'),
                        ('Tejutla', 'Tejutla'),
                        ('Tiquisate', 'Tiquisate'),
                        ('Todos Santos Cuchumatán', 'Todos Santos Cuchumatán'),
                        ('Totonicapán', 'Totonicapán'),
                        ('Tucurú', 'Tucurú'),
                        ('Unión Cantinil', 'Unión Cantinil'),
                        ('Uspantán', 'Uspantán'),
                        ('Usumatlán', 'Usumatlán'),
                        ('Villa Canales', 'Villa Canales'),
                        ('Villa Nueva', 'Villa Nueva'),
                        ('Yepocapa', 'Yepocapa'),
                        ('Zacapa', 'Zacapa'),
                        ('Zacualpa', 'Zacualpa'),
                        ('Zapotitlán', 'Zapotitlán'),
                        ('Zaragoza', 'Zaragoza'),
                        ('Zunil', 'Zunil'),
                        ('Zunilito', 'Zunilito')]




AltaVerapazList = ['Cahabón','Chahal','Chisec','Cobán', 'Fray Bartolomé de Las Casas','Lanquín', 'Panzós', 'Raxruhá', 'San Cristóbal Verapaz', 'San Juan Chamelco', 'San Pedro Carchá', 'Santa Catalina La Tinta','Santa Cruz Verapaz', 'Senahú', 'Tactic', 'Tamahú', 'Tucurú' ]

BajaVerapazList = ['Cubulco','El Chol','Granados','Purulhá','Rabinal','Salamá','San Jerónimo','San Miguel Chicaj']

ChimaltenangoList = ['Acatenango','Chimaltenango', 'Comalapa', 'El Tejar', 'Santa Apolonia', 'Parramos', 'Patzicía', 'Patzún', 'Pochuta', 'San Andrés Itzapa', 'San José Poaquil','San Martín Jilotepeque', 'Santa Cruz Balanyá', 'Tecpán Guatemala', 'Yepocapa', 'Zaragoza']

Chiquimula = ['Camotán', 'Chiquimula', 'Concepción Las Minas', 'Esquipulas', 'Ipala', 'Jocotán', 'San Jacinto', 'Olopa', 'Quezaltepeque', 'San José La Arada', 'San Juan Ermita']

ElProgresoList = ['El Jícaro', 'Guastatoya', 'Morazán', 'San Agustín Acasaguastlán', 'San Antonio La Paz', 'San Cristóbal Acasaguastlán', 'Sanarate', 'Sansare']

EscuintlaList = ['Iztapa', 'Escuintla', 'Guanagazapa', 'La Democracia', 'La Gomera', 'Masagua', 'Nueva Concepción', 'Palín', 'San José', 'San Vicente Pacaya', 'Santa Lucía Cotzumalguapa', 'Sipacate', 'Siquinalá', 'Tiquisate']

GuatemalaList = ['Amatitlán', 'Chinautla', 'Chuarrancho', 'Fraijanes', 'Guatemala', 'Lago De Amatitlan', 'Mixco', 'Palencia', 'Petapa', 'San José del Golfo', 'San José Pinula', 'San Juan Sacatepéquez', 'San Pedro Ayampuc', 'San Pedro Sacatepéquez', 'San Raimundo', 'Santa Catarina Pinula', 'Villa Canales', 'Villa Nueva']

HuehuetenangoList = ['Aguacatán', 'Barillas', 'Chiantla', 'Colotenango', 'Concepción Huista', 'San Gaspar Ixchil', 'Cuilco', 'Ixtahuacán', 'Huehuetenango', 'Jacaltenango', 'La Libertad', 'La Democracia', 'Malacatancito', 'San Sebastián Huehuetenango', 'Nentón', 'Petatán', 'San Antonio Huista', 'San Juan Atitán', 'San Juan Ixcoy', 'San Mateo Ixtatán', 'San Miguel Acatán', 'San Pedro Necta', 'San Rafael La Independencia', 'San Rafael Petzal', 'San Sebastián Coatán', 'Santa Ana Huista', 'Santa Bárbara', 'Santa Eulalia', 'Santiago Chimaltenango', 'Soloma', 'Tectitán', 'Todos Santos Cuchumatán', 'Unión Cantinil']

IzabalList = ['El Estor', 'Lívingston', 'Los Amates', 'Morales', 'Puerto Barrios']

JalapaList = ['Jalapa', 'Mataquescuintla', 'Monjas', 'San Carlos Alzatate', 'San Luis Jilotepeque', 'San Manuel Chaparrón', 'San Pedro Pinula']

JutiapaList = ['Agua Blanca', 'Asunción Mita', 'Atescatempa', 'El Adelanto', 'Comapa', 'Conguaco', 'El Progreso', 'Jalpatagua', 'Jerez', 'Jutiapa', 'Moyuta', 'San José Acatempa', 'Pasaco', 'Quesada', 'Santa Catarina Mita', 'Yupiltepeque', 'Zapotitlán']

PetenList = ['Dolores', 'El Chal', 'Flores', 'La Libertad', 'Melchor de Mencos', 'Las Cruces', 'San Benito', 'Poptún', 'San Andrés', 'San Francisco', 'San José', 'San Luis', 'Santa Ana', 'Sayaxché']

QuetzaltenangoList = ['Almolonga', 'Cabricán', 'Cantel', 'Cajolá', 'Coatepeque', 'Colomba', 'Concepción Chiquirichapa', 'El Palmar', 'Palestina de Los Altos', 'Flores Costa Cuca', 'Génova', 'Huitán', 'La Esperanza', 'Olintepeque', 'Ostuncalco', 'Quetzaltenango', 'Salcajá', 'San Carlos Sija', 'San Francisco La Unión', 'San Miguel Sigüila', 'San Martín Sacatepéquez', 'San Mateo', 'Sibilia', 'Zunil']

QuicheList = ['Chinique', 'Canillá', 'Chajul', 'Chichicastenango', 'Chicamán', 'Chiché', 'Cunén', 'Ixcán', 'Joyabaj', 'Nebaj', 'Pachalum', 'Patzité', 'Sacapulas', 'San Andrés Sajcabajá', 'San Antonio Ilotenango', 'San Bartolomé Jocotenango', 'San Juan Cotzal', 'San Pedro Jocopilas', 'Santa Cruz del Quiché', 'Uspantán', 'Zacualpa']

RetalhuleuList = ['Champerico', 'El Asintal', 'Nuevo San Carlos', 'Retalhuleu', 'San Andrés Villa Seca', 'San Felipe', 'San Martín Zapotitlán', 'San Sebastián', 'Santa Cruz Muluá']

SacatepequezList = ['Alotenango', 'Antigua Guatemala', 'Ciudad Vieja', 'Jocotenango', 'San Bartolomé Milpas Altas', 'Magdalena Milpas Altas', 'San Lucas Sacatepéquez', 'Pastores', 'San Antonio Aguas Calientes', 'San Miguel Dueñas', 'Santa Catarina Barahona', 'Santa Lucía Milpas Altas', 'Santo Domingo Xenacoj', 'Santa María de Jesús', 'Santiago Sacatepéquez', 'Sumpango']

SanMarcosList = ['Ayutla', 'Catarina', 'Comitancillo', 'Concepción Tutuapa', 'El Quetzal', 'El Rodeo', 'El Tumbador', 'Esquipulas Palo Gordo', 'Ixchiguán', 'San Antonio Sacatepéquez', 'La Blanca', 'La Reforma', 'Malacatán', 'Nuevo Progreso', 'Ocós', 'Pajapita', 'San José Ojetenam', 'San Cristóbal Cucho', 'Río Blanco', 'San Lorenzo', 'San Marcos', 'San Miguel Ixtahuacán', 'San Pablo', 'San Rafael Pie de la Cuesta', 'San Pedro Sacatepéquez', 'Sibinal', 'Sipacapa', 'Tacaná', 'Tajumulco', 'Tejutla']

SantaRosaList = ['Barberena', 'Casillas', 'Chiquimulilla', 'Cuilapa', 'Guazacapán', 'Nueva Santa Rosa', 'Oratorio', 'Pueblo Nuevo Viñas', 'San Juan Tecuaco', 'San Rafael Las Flores', 'Santa Cruz Naranjo', 'Santa María Ixhuatán', 'Santa Rosa de Lima', 'Taxisco']

SololaList = ['Concepción', 'Santa María Visitación', 'Lago De Atitlan', 'Nahualá', 'San José Chacayá', 'Panajachel', 'San Andrés Semetabaj', 'San Antonio Palopó', 'San Juan La Laguna', 'San Lucas Tolimán', 'San Marcos La Laguna', 'San Pablo La Laguna', 'San Pedro La Laguna', 'Santa Clara La Laguna', 'Santa Catarina Ixtahuacán', 'Santa Cruz La Laguna', 'Santa Catarina Palopó', 'Santa Lucía Utatlán', 'Santiago Atitlán', 'Sololá']

SuchitepequezList = ['Chicacao', 'Cuyotenango', 'Santo Domingo Suchitepéquez', 'Mazatenango', 'San Bernardino', 'Patulul', 'Samayac', 'Pueblo Nuevo', 'Río Bravo', 'San Antonio Suchitepéquez', 'San Gabriel', 'San Francisco Zapotitlán', 'San José El Ídolo', 'San José La Máquina', 'San Juan Bautista', 'San Lorenzo', 'San Miguel Panán', 'San Pablo Jocopilas', 'Santa Bárbara', 'Santo Tomás La Unión', 'Zunilito']

TotonicapanList = ['Momostenango', 'San Andrés Xecul', 'San Cristóbal Totonicapán', 'San Bartolo', 'San Francisco El Alto', 'Santa Lucía La Reforma', 'Santa María Chiquimula', 'Totonicapán']

ZacapaList = ['Cabañas', 'Estanzuela', 'Gualán', 'Huité', 'La Unión', 'Río Hondo', 'San Diego', 'San Jorge', 'Teculután', 'Usumatlán', 'Zacapa']  


